save.connect("https://xstrstudios.wixsite.com/cc-api/connect/data-server")
load.ext(../connect/data-server)
def.TOKEN("cc-api")
def.ID("000425")
def.USER("CrazyCombatAPI")
def.PASS("**********")

#------------

start.data-server
request.data-server.mc-link

{|status-online}
{|logs-disabled}
{|"motion.play"-enable}

failed.recive.request(MC-link):
  - end.all
  - start.reroll.sync(@All)
  - def.alert
  - alert.send(USER:@YoThepro19,ID:none,msg:"losted data")
  - `Finish`
